---
functional:
  - Пользователь должен иметь возможность зарегестрироваться в приложении.
  - Пользователь должен иметь возможность добавить скрипт на свой сайт.
  - Пользователь должен иметь возможность отслеживать статус ошибком найденных на своем сайте через сервис.
  - Пользователь должен иметь возможность корректировать ошибки найденные на сайте через сервис.
  - Пользователь должен иметь возможность просматривать пространства.
  - Пользователь должен иметь возможность просматривать созданные простанства.
  - Пользователь должен иметь возможность дать имя пространству.
  - Пользователь должен иметь возможность описать пространство.
  - Пользователь должен иметь возможность добавлять пользователей в созданное пространство.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Пользователь должен иметь возможность зарегестрироваться в приложении.
  - Пользователь должен иметь возможность заказать товар.
  - Пользователь должен иметь возможность получить обратную связь о статусе заказа.
  - Пользователь должен иметь возможность отменить заказ.
  - Пользователь должен иметь возможность удалить товар из корзины.
  - Пользователь должен иметь возможность откладывать товар в избранное.
  - Информация, представленная на сайте, должна соотвествовать нормам законодательства Российской Федерации.
  - Информация на сайте должна быть представлена на русском и английском языках.
